// Generated by CoffeeScript 1.6.3
(function() {
  var CSAttributedString, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  CSAttributedString = (function() {
    function CSAttributedString(string, initialAttributes) {
      var k, v;
      this.string = string != null ? string : '';
      this.attributes = {};
      for (k in initialValues) {
        v = initialValues[k];
        this.attributes[k] = v;
      }
    }

    return CSAttributedString;

  })();

  root.CSAttributedString = CSAttributedString;

}).call(this);
