// Generated by CoffeeScript 1.6.3
(function() {
  var NSAttributedString, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  NSAttributedString = (function() {
    function NSAttributedString(string, attributedRanges) {
      this.string = string != null ? string : '';
      this.attributedRanges = attributedRanges != null ? attributedRanges : [];
    }

    return NSAttributedString;

  })();

  root.NSAttributedString = NSAttributedString;

}).call(this);
